#!/usr/bin/env bash

set -euo pipefail

if [[ ! -z ${VERBOSE+x} ]]; then
  set -x
fi

BINS="$HOME/.cache/bin"

DCOS_LOGIN="$BINS/dcos-login"

mkdir -p "$BINS"

LATEST_RELEASE="$(curl -sSL -u "bowbaq:$GITHUB_TOKEN" https://api.github.com/repos/Originate/dcos-login/releases/latest)"
LATEST_DOWNLOAD_URL=$(jq -r '.assets[] | select(.name == "dcos-login_linux_amd64") | .url' <<< "$LATEST_RELEASE")
curl -sSL -u "bowbaq:$GITHUB_TOKEN" -H 'Accept: application/octet-stream' "$LATEST_DOWNLOAD_URL" -o "$DCOS_LOGIN"
chmod u+x "$DCOS_LOGIN"
