#!/usr/bin/env bash

set -euo pipefail

if [[ ! -z ${VERBOSE+x} ]]; then
  set -x
fi

JOB="$1"
JOB_MANIFEST="$JOB/job.json"
JOB_SCHEDULE="$JOB/schedule.json"
JOB_ID="$(jq -r '.id' "$JOB_MANIFEST")"

# This returns true if the job currently exists in Metronome (e.g. needs to be updated instead of created)
function job_exists() {
  local job_id="$1"

  dcos job list --json | jq  -r '.[].id' | grep -Eq "^$job_id$"
}

if job_exists "$JOB_ID"; then
  dcos job update "$JOB_MANIFEST"
  # Running `dcos job update` with an embdedded schedules doesn't work
  dcos job schedule update "$JOB_ID" "$JOB_SCHEDULE"
else
  dcos job add "$JOB_MANIFEST"
  dcos job schedule add "$JOB_ID" "$JOB_SCHEDULE"
fi
